# Advanced Data Manipulation and Visualization

This notebook is dedicated to practicing different tasks with pandas, numpy and matplotlib.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [pandas documentation](https://pandas.pydata.org/pandas-docs/stable/).

In [2]:
# Import pandas
import pandas as pd
import numpy as np

AttributeError: partially initialized module 'pandas' from 'c:\Users\Lenovo\miniconda3\envs\myenv\Lib\site-packages\pandas\__init__.py' has no attribute '_pandas_parser_CAPI' (most likely due to a circular import)

In [ ]:
# Create a series of three different colours
colors = pd.Series(["Blue", "Red", "Green"],name="colors")

In [ ]:
# View the series of different colours
colors.to_frame()
# fruits.to_frame()

  colors
0   Blue
1    Red
2  Green

In [ ]:
# Create a series of three different car types and view it
cars = pd.Series(["Pajero", "BMW", "Civic"],name="cars")
cars.to_frame()

     cars
0  Pajero
1     BMW
2   Civic

In [ ]:
# Combine the Series of cars and colours into a DataFrame
df = pd.DataFrame({"Car Types": cars, "Colors": colors})

df

  Car Types Colors
0    Pajero   Blue
1       BMW    Red
2     Civic  Green

In [ ]:
# Import "/data/car-sales.csv" and turn it into a DataFrame
car_sales = pd.read_csv("../../data/car-sales.csv")
car_sales

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

**Note:** Since you've imported `../data/car-sales.csv` as a DataFrame, we'll now refer to this DataFrame as 'the car sales DataFrame'.

In [ ]:
# Export the DataFrame you created to a .csv file
df.to_csv("a.csv" , index=False)

In [ ]:
# Find the different datatypes of the car data DataFrame
car_sales.dtypes

Make             object
Colour           object
Odometer (KM)     int64
Doors             int64
Price            object
dtype: object

In [ ]:
# Describe your current car sales DataFrame using describe()
car_sales.describe()

       Odometer (KM)      Doors
count      10.000000  10.000000
mean    78601.400000   4.000000
std     61983.471735   0.471405
min     11179.000000   3.000000
25%     35836.250000   4.000000
50%     57369.000000   4.000000
75%     96384.500000   4.000000
max    213095.000000   5.000000

In [ ]:
# Get information about your DataFrame using info()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Car Types  3 non-null      object
 1   Colors     3 non-null      object
dtypes: object(2)
memory usage: 180.0+ bytes

What does it show you?

In [ ]:
# Create a Series of different numbers and find the mean of them
series = pd.Series([999, 22203, 43920])
series.mean()

np.float64(22374.0)

In [ ]:
# Create a Series of different numbers and find the sum of them

numbers=pd.Series([200,300,500,988,273,645])
print(numbers.sum())

2906

In [ ]:
# List out all the column names of the car sales DataFrame
print(car_sales.keys().to_list())
list(car_sales)
# df.columns.values.tolist()
# df.columns.to_list()

['Make', 'Colour', 'Odometer (KM)', 'Doors', 'Price']

['Make', 'Colour', 'Odometer (KM)', 'Doors', 'Price']

In [ ]:
# Find the length of the car sales DataFrame , hint: len()
len(car_sales["Colour"])
len(car_sales)

10

In [ ]:
# Show the first 5 rows of the car sales DataFrame, hint: head()
car_sales.head()

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00

In [ ]:
# Show the first 7 rows of the car sales DataFrame
car_sales.head(n=7)

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00

In [ ]:
# Show the bottom 5 rows of the car sales DataFrame
car_sales.tail()

     Make Colour  Odometer (KM)  Doors      Price
5  Toyota  Green          99213      4  $4,500.00
6   Honda   Blue          45698      4  $7,500.00
7   Honda   Blue          54738      4  $7,000.00
8  Toyota  White          60000      4  $6,250.00
9  Nissan  White          31600      4  $9,700.00

In [ ]:
# Use .loc to select the row at index 3 of the car sales DataFrame
# .loc is used to access rows and column through lables 
# creating a sample dataframe
data = pd.DataFrame({'Brand': ['Maruti', 'Hyundai', 'Tata',
                               'Mahindra', 'Maruti', 'Hyundai',
                               'Renault', 'Tata', 'Maruti'],
                     'Year': [2012, 2014, 2011, 2015, 2012,
                              2016, 2014, 2018, 2019],
                     'Kms Driven': [50000, 30000, 60000,
                                    25000, 10000, 46000,
                                    31000, 15000, 12000],
                     'City': ['Gurgaon', 'Delhi', 'Mumbai',
                              'Delhi', 'Mumbai', 'Delhi',
                              'Mumbai', 'Chennai',  'Ghaziabad'],
                     'Mileage':  [28, 27, 25, 26, 28,
                                  29, 24, 21, 24]})

# displaying the DataFrame
display(data)
data.loc[3]
data.loc[data.Brand == "Tata" ,["City","Year"]]
data.loc[1:3,["City","Year"]]

      Brand  Year  Kms Driven       City  Mileage
0    Maruti  2012       50000    Gurgaon       28
1   Hyundai  2014       30000      Delhi       27
2      Tata  2011       60000     Mumbai       25
3  Mahindra  2015       25000      Delhi       26
4    Maruti  2012       10000     Mumbai       28
5   Hyundai  2016       46000      Delhi       29
6   Renault  2014       31000     Mumbai       24
7      Tata  2018       15000    Chennai       21
8    Maruti  2019       12000  Ghaziabad       24

     City  Year
1   Delhi  2014
2  Mumbai  2011
3   Delhi  2015

In [ ]:
# Use .iloc to select the row at position 3 of the car sales DataFrame
display(car_sales)
car_sales.iloc[3]

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

Make                    BMW
Colour                Black
Odometer (KM)         11179
Doors                     5
Price            $22,000.00
Name: 3, dtype: object

Notice how they're the same? Why do you think this is?

Check the pandas documentation for [.loc](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.loc.html) and [.iloc](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.iloc.html). Think about a different situation each could be used for and try them out.

In [ ]:
# Selcect the "Odometer (KM)" column from the car sales DataFrame
car_sales["Odometer (KM)"]

0    150043
1     87899
2     32549
3     11179
4    213095
5     99213
6     45698
7     54738
8     60000
9     31600
Name: Odometer (KM), dtype: int64

In [ ]:
# Find the mean of the "Odometer (KM)" column in the car sales DataFrame
print(car_sales["Odometer (KM)"].mean())

78601.4

In [ ]:
# Select the rows with over 100,000 kilometers on the Odometer
rows = car_sales.loc[car_sales["Odometer (KM)"]> 100000]
rows

     Make Colour  Odometer (KM)  Doors      Price
0  Toyota  White         150043      4  $4,000.00
4  Nissan  White         213095      4  $3,500.00

In [ ]:
# Create a crosstab of the Make and Doors columns
pd.crosstab(car_sales["Make"], car_sales["Doors"])

Doors   3  4  5
Make
BMW     0  0  1
Honda   0  3  0
Nissan  0  2  0
Toyota  1  3  0

In [ ]:
# Group columns of the car sales DataFrame by the Make column and find the average
car_sales['Price']=car_sales["Price" ].str.replace('$','').str.replace(',','').astype(float)

In [ ]:
# Change the datatype of the Price column to integers
car_sales.groupby('Make')['Price'].mean()

Make
BMW       22000.0
Honda      6500.0
Nissan     6600.0
Toyota     5437.5
Name: Price, dtype: float64

Now let's deal with missing data.

In [ ]:
# Import the car sales DataFrame with missing data ("/data/car-sales-missing-data.csv")

missing_values=pd.read_csv('./../../data/car-sales-missing-data.csv')
missing_values.head()

missing_values.isnull().sum().sort_values(ascending=False)

# Check out the new DataFrame

Odometer    4
Price       2
Make        1
Colour      1
Doors       1
dtype: int64

Notice the missing values are represented as `NaN` in pandas DataFrames.

Let's try fill them.

In [ ]:
# Fill the Odometer column missing values with the mean of the column inplace
missing_values['Odometer'].fillna(missing_values['Odometer'].median(), inplace=True)

missing_values.isnull().sum().sort_values(ascending=False)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_21848\965304189.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  missing_values['Odometer'].fillna(missing_values['Odometer'].median(), inplace=True)

Price       2
Make        1
Colour      1
Doors       1
Odometer    0
dtype: int64

In [ ]:
# View the car sales missing DataFrame and verify the changes
missing_values.isnull().sum().sort_values(ascending=False)

Price       2
Make        1
Colour      1
Doors       1
Odometer    0
dtype: int64

In [ ]:
# Remove the rest of the missing data inplace
missing_values=missing_values.dropna()
missing_values.isnull().sum().sort_values(ascending=False)

Make        0
Colour      0
Odometer    0
Doors       0
Price       0
dtype: int64

In [ ]:
# Verify the missing values are removed by viewing the DataFrame
missing_values.isnull().sum().sort_values(ascending=False)

Make        0
Colour      0
Odometer    0
Doors       0
Price       0
dtype: int64

We'll now start to add columns to our DataFrame.

In [ ]:
# Create a "Seats" column where every row has a value of 5
car_sales["Seats"] = 5
car_sales

     Make Colour  Odometer (KM)  Doors    Price  Seats
0  Toyota  White         150043      4   4000.0      5
1   Honda    Red          87899      4   5000.0      5
2  Toyota   Blue          32549      3   7000.0      5
3     BMW  Black          11179      5  22000.0      5
4  Nissan  White         213095      4   3500.0      5
5  Toyota  Green          99213      4   4500.0      5
6   Honda   Blue          45698      4   7500.0      5
7   Honda   Blue          54738      4   7000.0      5
8  Toyota  White          60000      4   6250.0      5
9  Nissan  White          31600      4   9700.0      5

In [ ]:
# Create a column called "Engine Size" with random values between 1.3 and 4.5
# Remember: If you're doing it from a Python list, the list has to be the same length
# as the DataFrame
length=len(car_sales)
car_sales["Engine Size"]= (np.random.uniform(1.3,4.5 ,size=length))
car_sales

     Make Colour  Odometer (KM)  Doors    Price  Seats  Engine Size
0  Toyota  White         150043      4   4000.0      5     2.792035
1   Honda    Red          87899      4   5000.0      5     3.260504
2  Toyota   Blue          32549      3   7000.0      5     3.383292
3     BMW  Black          11179      5  22000.0      5     2.125038
4  Nissan  White         213095      4   3500.0      5     1.656345
5  Toyota  Green          99213      4   4500.0      5     4.366862
6   Honda   Blue          45698      4   7500.0      5     1.740655
7   Honda   Blue          54738      4   7000.0      5     3.175656
8  Toyota  White          60000      4   6250.0      5     3.096111
9  Nissan  White          31600      4   9700.0      5     3.613999

In [ ]:
# Create a column which represents the price of a car per kilometer
car_sales['Price per KM'] = car_sales['Price'] / car_sales ['Odometer (KM)']
# Then view the DataFrame
car_sales

,Make,Colour,Odometer (KM),Doors,Price,Seats,Engine Size,Price per KM
0,Toyota,White,150043,4,4000.0,5,2.792035,0.026659
1,Honda,Red,87899,4,5000.0,5,3.260504,0.056883
2,Toyota,Blue,32549,3,7000.0,5,3.383292,0.215060
3,BMW,Black,11179,5,22000.0,5,2.125038,1.967976
4,Nissan,White,213095,4,3500.0,5,1.656345,0.016425
5,Toyota,Green,99213,4,4500.0,5,4.366862,0.045357
6,Honda,Blue,45698,4,7500.0,5,1.740655,0.164121
7,Honda,Blue,54738,4,7000.0,5,3.175656,0.127882
8,Toyota,White,60000,4,6250.0,5,3.096111,0.104167
9,Nissan,White,31600,4,9700.0,5,3.613999,0.306962

In [ ]:
# Remove the last column you added using .drop()
car_sales.drop('Price per KM', axis=1 ,inplace=True)
car_sales

     Make Colour  Odometer (KM)  Doors    Price  Seats  Engine Size
0  Toyota  White         150043      4   4000.0      5     2.792035
1   Honda    Red          87899      4   5000.0      5     3.260504
2  Toyota   Blue          32549      3   7000.0      5     3.383292
3     BMW  Black          11179      5  22000.0      5     2.125038
4  Nissan  White         213095      4   3500.0      5     1.656345
5  Toyota  Green          99213      4   4500.0      5     4.366862
6   Honda   Blue          45698      4   7500.0      5     1.740655
7   Honda   Blue          54738      4   7000.0      5     3.175656
8  Toyota  White          60000      4   6250.0      5     3.096111
9  Nissan  White          31600      4   9700.0      5     3.613999

In [ ]:
# Change the title of the Odometer (KM) to represent miles instead of kilometers
car_sales= car_sales.rename(columns={'Odometer (KM)':'Odometer (Mile)'})
car_sales

     Make Colour  Odometer (Mile)  Doors    Price  Seats  Engine Size
0  Toyota  White           150043      4   4000.0      5     2.792035
1   Honda    Red            87899      4   5000.0      5     3.260504
2  Toyota   Blue            32549      3   7000.0      5     3.383292
3     BMW  Black            11179      5  22000.0      5     2.125038
4  Nissan  White           213095      4   3500.0      5     1.656345
5  Toyota  Green            99213      4   4500.0      5     4.366862
6   Honda   Blue            45698      4   7500.0      5     1.740655
7   Honda   Blue            54738      4   7000.0      5     3.175656
8  Toyota  White            60000      4   6250.0      5     3.096111
9  Nissan  White            31600      4   9700.0      5     3.613999

# Numpy Operations

In [ ]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [ ]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1,2,3])

# Create a 2-dimensional NumPy array using np.array()
a2= np.array([[1,2,3],[4,5,6]])
a2
# Create a 3-dimensional Numpy array using np.array()
a3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[11,12,13]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [11, 12, 13]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [ ]:
# Attributes of 1-dimensional array | number of dimensions, data type, size and type)
# (shape, ndim, dtype, size, type())
a1.shape, a1.ndim, a1.dtype, a1.size, type(a1)

((3,), 1, dtype('int64'), 3, numpy.ndarray)

In [ ]:
# Attributes of 2-dimensional array
a2.shape, a2.ndim,a2.dtype, a2.size

((2, 3), 2, dtype('int64'), 6)

In [ ]:
# Attributes of 3-dimensional array
a3.shape, a3.ndim,a3.dtype, a3.size

((2, 2, 3), 3, dtype('int64'), 12)

In [ ]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
pd.DataFrame(data=a2, columns=['A', 'B','C'] )

   A  B  C
0  1  2  3
1  4  5  6

In [ ]:
# Create an array of shape (10, 2) with only ones
arr_ones=np.ones([10,2])
arr_ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
# Create an array of shape (7, 2, 3) of only zeros
arr_zeros=np.zeros([7,2,3])
arr_zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
# Create an array within a range of 0 and 100 with step 3
arrnaged= np.arange(1,100,3)
arrnaged

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
       52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97])

In [ ]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_array= np.random.randint(0,10, size=(7,2))
random_array

array([[7, 7],
       [7, 2],
       [7, 6],
       [4, 4],
       [0, 5],
       [1, 0],
       [1, 2]], dtype=int32)

In [ ]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
floats_rand= np.random.rand(3,5)
floats_rand

array([[0.89116277, 0.90281318, 0.62134817, 0.16671365, 0.14206261],
       [0.50623263, 0.24073181, 0.60601193, 0.19659464, 0.08567492],
       [0.17325125, 0.69863714, 0.83999583, 0.5949971 , 0.08360171]])

In [ ]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
random_array1 = np.random.randint(0,10, size=(4,6))
random_array

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]], dtype=int32)

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [ ]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
random_array2= np.random.randint(0,10, size=(3,7))
random_array2
np.unique(random_array2)

# Find the unique numbers in the array you just created

array([0, 1, 2, 3, 6, 7, 8, 9], dtype=int32)

In [ ]:
# Find the 0'th index of the latest array you created
random_array2[0]

array([1, 4, 9, 5, 6, 3, 6], dtype=int32)

In [ ]:
# Get the first 2 rows of latest array you created
print(random_array2[:2, 0:])

[[3 2 9 2 2 3 6]
 [3 8 0 7 6 1 7]]

In [ ]:
# Get the first 2 values of the first 2 rows of the latest array
print(random_array2[:1, 0:2])

[[3 2]]

In [ ]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
random_array3= np.random.randint(0,10, size=(3,5))
arr_ones_2= np.ones([3,5])
print(random_array3)
print(arr_ones_2)

[[9 6 9 2 1]
 [8 7 9 6 8]
 [3 3 0 7 2]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

In [ ]:
# Add the two arrays together
np.concatenate( (random_array3, arr_ones_2) , axis=0)

array([[9., 6., 9., 2., 1.],
       [8., 7., 9., 6., 8.],
       [3., 3., 0., 7., 2.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# Create another array of ones of shape (5, 3)

In [ ]:
# Try add the array of ones and the other most recent array together

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [ ]:
# Create another array of ones of shape (3, 5)

In [ ]:
# Subtract the new array of ones from the other most recent array

In [ ]:
# Multiply the ones array with the latest array

In [ ]:
# Take the latest array to the power of 2 using '**'

In [ ]:
# Do the same thing with np.square()

In [ ]:
# Find the mean of the latest array using np.mean()

In [ ]:
# Find the maximum of the latest array using np.max()

In [ ]:
# Find the minimum of the latest array using np.min()

In [ ]:
# Find the standard deviation of the latest array

In [ ]:
# Find the variance of the latest array

In [ ]:
# Reshape the latest array to (3, 5, 1)

In [ ]:
# Transpose the latest array

What does the transpose do?

In [ ]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)

In [ ]:
# Perform a dot product on the two newest arrays you created

In [ ]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)

In [ ]:
# Perform a dot product on the two newest arrays you created, hint: np.dot()

It doesn't work. How would you fix it?

In [ ]:
# Take the latest two arrays, perform a transpose on one of them and then perform
# a dot product on them both

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [ ]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables

In [ ]:
# Compare the two arrays with '>'

What happens when you compare the arrays with `>`?

In [ ]:
# Compare the two arrays with '>='

In [ ]:
# Find which elements of the first array are greater than 7

In [ ]:
# Which parts of each array are equal? (try using '==')

In [ ]:
# Sort one of the arrays you just created in ascending order

In [ ]:
# Sort the indexes of one of the arrays you just created

In [ ]:
# Find the index with the maximum value in one of the arrays you've created

In [ ]:
# Find the index with the minimum value in one of the arrays you've created

In [ ]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created

In [ ]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created

In [ ]:
# Create an array of normally distributed random numbers

In [ ]:
# Create an array with 10 evenly spaced numbers between 1 and 100

#Data Visulization with Matplotlib

In [ ]:
# Import the pyplot module from matplotlib as plt and make sure
# plots appear in the notebook using '%matplotlib inline'
%matplotlib inline
import matplotlib.pyplot as plt

In [ ]:
# Create a simple plot using plt.plot()

In [ ]:
# Plot a single Python list

In [ ]:
# Create two lists, one called X, one called y, each with 5 numbers in them
X = [22, 88, 98, 103, 45]
y = [7, 8, 9, 10, 11]

In [ ]:
# Plot X & y (the lists you've created)

There's another way to create plots with Matplotlib, it's known as the object-orientated (OO) method. Let's try it.

In [ ]:
# Create a plot using plt.subplots()
fig, ax = plt.subplots()

In [ ]:
# Create a plot using plt.subplots() and then add X & y on the axes
fig, ax = plt.subplots()
ax.plot(X, y)

Now let's try a small matplotlib workflow.

In [ ]:
# Import and get matplotlib ready


# Prepare data (create two lists of 5 numbers, X & y)


# Setup figure and axes using plt.subplots()


# Add data (X, y) to axes


# Customize plot by adding a title, xlabel and ylabel
ax.set(title="Sample simple plot",
       xlabel="x-axis",
       ylabel="y-axis")

# Save the plot to file using fig.savefig()
fig.savefig("/images/simple-plot.png")

Okay, this is a simple line plot, how about something a little different?

To help us, we'll import NumPy.

In [ ]:
# Import NumPy as np

In [ ]:
# Create an array of 100 evenly spaced numbers between 0 and 100 using NumPy and save it to variable X

In [ ]:
# Create a plot using plt.subplots() and plot X versus X^2 (X squared)

We'll start with scatter plots.

In [ ]:
# Create a scatter plot of X versus the exponential of X (np.exp(X))
fig, ax = plt.subplots()
ax.scatter(X, np.exp(X))

In [ ]:
# Create a scatter plot of X versus np.sin(X)

How about we try another type of plot? This time let's look at a bar plot. First we'll make some data.

In [ ]:
# Create a Python dictionary of 3 of your favourite foods with
# The keys of the dictionary should be the food name and the values their price

In [ ]:
# Create a bar graph where the x-axis is the keys of the dictionary
# and the y-axis is the values of the dictionary
fig, ax = plt.subplots()
ax.bar(favourite_food_prices.keys(), favourite_food_prices.values())

# Add a title, xlabel and ylabel to the plot
ax.set(title="My favourite foods",
       xlabel="Food",
       ylabel="Price ($)")

In [ ]:
# Make the same plot as above, except this time make the bars go horizontal, hint: use barh

All this food plotting is making me hungry. But we've got a couple of plots to go.

Let's see a histogram.

In [ ]:
# Create a random NumPy array of 1000 normally distributed numbers using NumPy and save it to X


# Create a histogram plot of X

In [ ]:
# Create a NumPy array of 1000 random numbers and save it to X


# Create a histogram plot of X

Notice how the distributions (spread of data) are different. Why do they differ?

What else can you find out about the normal distribution?

Can you think of any other kinds of data which may be normally distributed?

These questions aren't directly related to plotting or Matplotlib but they're helpful to think of.

Now let's try make some subplots. A subplot is another name for a figure with multiple plots on it.

In [ ]:
# Create an empty subplot with 2 rows and 2 columns (4 subplots total)
fig, ((ax1, ax2), (ax3, ax4)) = plt.subplots(nrows=2,
                                             ncols=2)

Notice how the subplot has multiple figures. Now let's add data to each axes.

In [ ]:
# Create the same plot as above with 2 rows and 2 columns and figsize of (10, 5)


# Plot X versus X/2 on the top left axes


# Plot a scatter plot of 10 random numbers on each axis on the top right subplot


# Plot a bar graph of the favourite food keys and values on the bottom left subplot


# Plot a histogram of 1000 random normally distributed numbers on the bottom right subplot

Woah. There's a lot going on there.

Now we've seen how to plot with Matplotlib and data directly. Let's practice using Matplotlib to plot with pandas.

First we'll need to import pandas and create a DataFrame work with.

In [ ]:
# Import pandas as pd

In [ ]:
# Import the '/data/car-sales.csv' into a DataFame called car_sales and view

In [ ]:
# Try to plot the 'Price' column using the plot() function

Why doesn't it work?

Hint: It's not numeric data.

In the process of turning it to numeric data, let's create another column which adds the total amount of sales and another one which shows what date the car was sold.

Hint: To add a column up cumulatively, look up the cumsum() function. And to create a column of dates, look up the date_range() function.

In [ ]:
# Remove the symbols, the final two numbers from the 'Price' column and convert it to numbers
car_sales["Price"] = car_sales["Price"].str.replace("[\$\,\.]", "")
car_sales["Price"] = car_sales["Price"].str[:-2]

In [ ]:
# Add a column called 'Total Sales' to car_sales which cumulatively adds the 'Price' column
car_sales["Total Sales"] = car_sales["Price"].astype(int).cumsum()

# Add a column called 'Sale Date' which lists a series of successive dates starting from today (your today)
car_sales["Sale Date"] = pd.date_range("13/1/2020", periods=len(car_sales))

# View the car_sales DataFrame
car_sales

Now we've got a numeric column (`Total Sales`) and a dates column (`Sale Date`), let's visualize them.

In [ ]:
# Use the plot() function to plot the 'Sale Date' column versus the 'Total Sales' column

In [ ]:
# Convert the 'Price' column to the integers
# write code here

# Create a scatter plot of the 'Odometer (KM)' and 'Price' column using the plot() function
car_sales.plot(x="Odometer (KM)", y="Price", kind="scatter")

In [ ]:
# Create a NumPy array of random numbers of size (10, 4) and save it to X


# Turn the NumPy array X into a DataFrame with columns called ['a', 'b', 'c', 'd']


# Create a bar graph of the DataFrame

In [ ]:
# Create a bar graph of the 'Make' and 'Odometer (KM)' columns in the car_sales DataFrame

In [ ]:
# Create a histogram of the 'Odometer (KM)' column

In [ ]:
# Create a histogram of the 'Price' column with 20 bins

Now we've seen a few examples of plotting directly from DataFrames using the `car_sales` dataset.

Let's try using a different dataset.

In [ ]:
# Import "/data/heart-disease.csv" and save it to the variable "heart_disease"

In [ ]:
# View the first 10 rows of the heart_disease DataFrame

In [ ]:
# Create a histogram of the "age" column with 50 bins

In [ ]:
# Call plot.hist() on the heart_disease DataFrame and toggle the
# "subplots" parameter to True

That plot looks pretty squished. Let's change the figsize.

In [ ]:
# Call the same line of code from above except change the "figsize" parameter
# to be (10, 30)

Now let's try comparing two variables versus the target variable.

More specifially we'll see how age and cholesterol combined effect the target in **patients over 50 years old**.

For this next challenge, we're going to be replicating the following plot:

<img src="../images/matplotlib-heart-disease-chol-age-plot.png"/>

In [ ]:
# Replicate the above plot in whichever way you see fit

# Note: The method below is only one way of doing it, yours might be
# slightly different

# Create DataFrame with patients over 50 years old


# Create the plot
fig, ax = plt.subplots(figsize=(10, 6))

# Plot the data
scatter = ax.scatter(over_50["age"],
                     over_50["chol"],
                     c=over_50["target"])


# Customize the plot
ax.set(title="Heart Disease and Cholesterol Levels",
       xlabel="Age",
       ylabel="Cholesterol");
ax.legend(*scatter.legend_elements(), title="Target")

# Add a meanline
ax.axhline(over_50["chol"].mean(),
           linestyle="--");

Beatiful, now you've created a plot of two different variables, let's change the style.

In [ ]:
# Save the current figure using savefig(), the file name can be anything you want

In [ ]:
# Reset the figure by calling plt.subplots()