#Decision Tree Classifier Lab

#Load essential libraries

In [203]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn import tree
from sklearn.model_selection import train_test_split

#Import the dataset

In [204]:
df = pd.read_csv("titanic.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

##Drop meaningless information

In [205]:
df = df.drop(columns = ['PassengerId','Name','SibSp', 'Parch', 'Ticket', 'Cabin', 'Embarked'], axis = 'columns')
df

     Survived  Pclass     Sex   Age     Fare
0           0       3    male  22.0   7.2500
1           1       1  female  38.0  71.2833
2           1       3  female  26.0   7.9250
3           1       1  female  35.0  53.1000
4           0       3    male  35.0   8.0500
..        ...     ...     ...   ...      ...
886         0       2    male  27.0  13.0000
887         1       1  female  19.0  30.0000
888         0       3  female   NaN  23.4500
889         1       1    male  26.0  30.0000
890         0       3    male  32.0   7.7500

[891 rows x 5 columns]

##Data Preprocessing

In [206]:
df.isna().sum()

Survived      0
Pclass        0
Sex           0
Age         177
Fare          0
dtype: int64

In [207]:
import math
mean_age = df.Age.mean()
mean_age = math.floor(mean_age)
print(mean_age)

29

In [208]:
df['Age'] = df.Age.fillna(mean_age)
df

     Survived  Pclass     Sex   Age     Fare
0           0       3    male  22.0   7.2500
1           1       1  female  38.0  71.2833
2           1       3  female  26.0   7.9250
3           1       1  female  35.0  53.1000
4           0       3    male  35.0   8.0500
..        ...     ...     ...   ...      ...
886         0       2    male  27.0  13.0000
887         1       1  female  19.0  30.0000
888         0       3  female  29.0  23.4500
889         1       1    male  26.0  30.0000
890         0       3    male  32.0   7.7500

[891 rows x 5 columns]

##Label Encode the non numeric features

In [209]:
LE_sex = LabelEncoder()
df['Sex'] = LE_sex.fit_transform(df['Sex'])

df

     Survived  Pclass  Sex   Age     Fare
0           0       3    1  22.0   7.2500
1           1       1    0  38.0  71.2833
2           1       3    0  26.0   7.9250
3           1       1    0  35.0  53.1000
4           0       3    1  35.0   8.0500
..        ...     ...  ...   ...      ...
886         0       2    1  27.0  13.0000
887         1       1    0  19.0  30.0000
888         0       3    0  29.0  23.4500
889         1       1    1  26.0  30.0000
890         0       3    1  32.0   7.7500

[891 rows x 5 columns]

## Define Feature Matrix (X) and Target Vector (y)

In [210]:
y = df['Survived']
X = df.drop('Survived', axis = 'columns')
X

     Pclass  Sex   Age     Fare
0         3    1  22.0   7.2500
1         1    0  38.0  71.2833
2         3    0  26.0   7.9250
3         1    0  35.0  53.1000
4         3    1  35.0   8.0500
..      ...  ...   ...      ...
886       2    1  27.0  13.0000
887       1    0  19.0  30.0000
888       3    0  29.0  23.4500
889       1    1  26.0  30.0000
890       3    1  32.0   7.7500

[891 rows x 4 columns]

In [211]:
df

     Survived  Pclass  Sex   Age     Fare
0           0       3    1  22.0   7.2500
1           1       1    0  38.0  71.2833
2           1       3    0  26.0   7.9250
3           1       1    0  35.0  53.1000
4           0       3    1  35.0   8.0500
..        ...     ...  ...   ...      ...
886         0       2    1  27.0  13.0000
887         1       1    0  19.0  30.0000
888         0       3    0  29.0  23.4500
889         1       1    1  26.0  30.0000
890         0       3    1  32.0   7.7500

[891 rows x 5 columns]

## Train-Test Split and Model Initialization

In [212]:
model = tree.DecisionTreeClassifier()

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.4)

##Train the model

In [213]:
model.fit(X_train, y_train)

model.score(X_test, y_test)
#model.score returns the mean accuracy for test data and labels

0.7787114845938375

In [214]:
X_test

     Pclass  Sex   Age     Fare
48        3    1  29.0  21.6792
647       1    1  56.0  35.5000
718       3    1  29.0  15.5000
466       2    1  29.0   0.0000
636       3    1  32.0   7.9250
..      ...  ...   ...      ...
107       3    1  29.0   7.7750
590       3    1  35.0   7.1250
447       1    1  34.0  26.5500
276       3    0  45.0   7.7500
808       2    1  39.0  13.0000

[357 rows x 4 columns]

##Predict results

In [215]:
model.predict([[1,0,19.0,91.0792]])

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([1])

In [216]:
y_test

48     0
647    1
718    0
466    0
636    0
      ..
107    1
590    0
447    1
276    0
808    0
Name: Survived, Length: 357, dtype: int64

##Try decision tree classifer on the same target column but this time use more feature columns than before.

In [220]:
df=pd.read_csv('titanic.csv')

features=['Pclass','Sex','Age','Fare','Embarked']


X=df[features]
y=df['Survived']



X=pd.concat([X,pd.get_dummies(X['Embarked'])],axis=1)

In [221]:
X=X.drop(['Embarked'],axis=1)
print(X)

     Pclass     Sex   Age     Fare      C      Q      S
0         3    male  22.0   7.2500  False  False   True
1         1  female  38.0  71.2833   True  False  False
2         3  female  26.0   7.9250  False  False   True
3         1  female  35.0  53.1000  False  False   True
4         3    male  35.0   8.0500  False  False   True
..      ...     ...   ...      ...    ...    ...    ...
886       2    male  27.0  13.0000  False  False   True
887       1  female  19.0  30.0000  False  False   True
888       3  female   NaN  23.4500  False  False   True
889       1    male  26.0  30.0000   True  False  False
890       3    male  32.0   7.7500  False   True  False

[891 rows x 7 columns]

In [225]:
lb=LabelEncoder()
X['Sex']=lb.fit_transform(X['Sex'])




model = tree.DecisionTreeClassifier()

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.4)
model.fit(X_train, y_train)

print("Score:",model.score(X_test, y_test))


print(model.predict(X_test))

Score: 0.7759103641456583
[1 0 0 0 0 1 0 1 0 0 0 0 0 0 0 1 0 0 0 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1
 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 1 0 0 1 1 0 0 0 0 0 0 0 0
 1 1 1 0 0 1 0 1 0 0 0 0 0 1 0 0 0 1 0 0 0 1 1 1 0 0 0 1 0 0 0 0 0 0 1 1 0
 0 0 1 1 0 0 1 1 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 1 1 1 1 1 0 1 0 0
 0 0 1 0 0 0 0 0 0 1 0 0 0 0 1 0 0 1 0 0 0 1 0 1 1 0 1 0 0 1 1 1 0 0 1 0 0
 1 0 1 0 0 1 0 0 1 0 1 0 1 1 0 0 1 0 1 0 0 1 0 1 0 1 1 1 0 0 1 1 1 0 0 0 0
 0 1 0 0 0 1 1 0 1 0 0 1 0 1 0 1 0 0 1 1 0 0 0 0 0 1 0 1 0 1 1 0 0 0 1 1 0
 0 0 0 0 1 1 0 0 0 1 0 1 1 1 1 0 0 0 1 0 0 0 1 1 1 1 1 0 0 1 0 0 0 1 0 0 0
 1 0 0 0 1 1 0 0 0 0 0 0 1 1 0 0 0 1 0 0 0 1 0 0 0 0 1 1 0 1 0 0 1 0 0 0 1
 1 1 1 1 1 1 0 1 0 1 0 1 0 1 0 1 1 1 0 1 0 1 1 0]